/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiWebhooksWompiRouteImport } from './routes/api/webhooks/wompi'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedOrgsNewRouteImport } from './routes/_authenticated/orgs/new'
import { Route as AuthenticatedOrgsSlugIndexRouteImport } from './routes/_authenticated/orgs/$slug/index'
import { Route as AuthenticatedOrgsSlugSettingsRouteImport } from './routes/_authenticated/orgs/$slug/settings'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugIndexRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/index'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/orders/$orderId'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/settings'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/details'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWebhooksWompiRoute = ApiWebhooksWompiRouteImport.update({
  id: '/api/webhooks/wompi',
  path: '/api/webhooks/wompi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsNewRoute = AuthenticatedOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsSlugIndexRoute =
  AuthenticatedOrgsSlugIndexRouteImport.update({
    id: '/orgs/$slug/',
    path: '/orgs/$slug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugSettingsRoute =
  AuthenticatedOrgsSlugSettingsRouteImport.update({
    id: '/orgs/$slug/settings',
    path: '/orgs/$slug/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugIndexRouteImport.update({
    id: '/orgs/$slug/profiles/$profileSlug/',
    path: '/orgs/$slug/profiles/$profileSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteImport.update({
    id: '/orgs/$slug/profiles/$profileSlug/_profile-settings',
    path: '/orgs/$slug/profiles/$profileSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRouteImport.update({
    id: '/orgs/$slug/profiles/$profileSlug/orders/$orderId',
    path: '/orgs/$slug/profiles/$profileSlug/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute,
    } as any,
  )
const AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRouteImport.update(
    {
      id: '/details',
      path: '/details',
      getParentRoute: () =>
        AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/wompi': typeof ApiWebhooksWompiRoute
  '/orgs/$slug/settings': typeof AuthenticatedOrgsSlugSettingsRoute
  '/orgs/$slug/': typeof AuthenticatedOrgsSlugIndexRoute
  '/orgs/$slug/profiles/$profileSlug': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteWithChildren
  '/orgs/$slug/profiles/$profileSlug/': typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
  '/orgs/$slug/profiles/$profileSlug/details': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute
  '/orgs/$slug/profiles/$profileSlug/settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute
  '/orgs/$slug/profiles/$profileSlug/orders/$orderId': typeof AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/wompi': typeof ApiWebhooksWompiRoute
  '/orgs/$slug/settings': typeof AuthenticatedOrgsSlugSettingsRoute
  '/orgs/$slug': typeof AuthenticatedOrgsSlugIndexRoute
  '/orgs/$slug/profiles/$profileSlug': typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
  '/orgs/$slug/profiles/$profileSlug/details': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute
  '/orgs/$slug/profiles/$profileSlug/settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute
  '/orgs/$slug/profiles/$profileSlug/orders/$orderId': typeof AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/wompi': typeof ApiWebhooksWompiRoute
  '/_authenticated/orgs/$slug/settings': typeof AuthenticatedOrgsSlugSettingsRoute
  '/_authenticated/orgs/$slug/': typeof AuthenticatedOrgsSlugIndexRoute
  '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteWithChildren
  '/_authenticated/orgs/$slug/profiles/$profileSlug/': typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
  '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/details': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute
  '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute
  '/_authenticated/orgs/$slug/profiles/$profileSlug/orders/$orderId': typeof AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/dashboard'
    | '/api/uploadthing'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/new'
    | '/api/auth/callback'
    | '/api/webhooks/stripe'
    | '/api/webhooks/wompi'
    | '/orgs/$slug/settings'
    | '/orgs/$slug/'
    | '/orgs/$slug/profiles/$profileSlug'
    | '/orgs/$slug/profiles/$profileSlug/'
    | '/orgs/$slug/profiles/$profileSlug/details'
    | '/orgs/$slug/profiles/$profileSlug/settings'
    | '/orgs/$slug/profiles/$profileSlug/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/dashboard'
    | '/api/uploadthing'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/new'
    | '/api/auth/callback'
    | '/api/webhooks/stripe'
    | '/api/webhooks/wompi'
    | '/orgs/$slug/settings'
    | '/orgs/$slug'
    | '/orgs/$slug/profiles/$profileSlug'
    | '/orgs/$slug/profiles/$profileSlug/details'
    | '/orgs/$slug/profiles/$profileSlug/settings'
    | '/orgs/$slug/profiles/$profileSlug/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/dashboard'
    | '/api/uploadthing'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_authenticated/orgs/new'
    | '/api/auth/callback'
    | '/api/webhooks/stripe'
    | '/api/webhooks/wompi'
    | '/_authenticated/orgs/$slug/settings'
    | '/_authenticated/orgs/$slug/'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/details'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/settings'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWebhooksWompiRoute: typeof ApiWebhooksWompiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/webhooks/wompi': {
      id: '/api/webhooks/wompi'
      path: '/api/webhooks/wompi'
      fullPath: '/api/webhooks/wompi'
      preLoaderRoute: typeof ApiWebhooksWompiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/new': {
      id: '/_authenticated/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AuthenticatedOrgsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/': {
      id: '/_authenticated/orgs/$slug/'
      path: '/orgs/$slug'
      fullPath: '/orgs/$slug/'
      preLoaderRoute: typeof AuthenticatedOrgsSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/settings': {
      id: '/_authenticated/orgs/$slug/settings'
      path: '/orgs/$slug/settings'
      fullPath: '/orgs/$slug/settings'
      preLoaderRoute: typeof AuthenticatedOrgsSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/'
      path: '/orgs/$slug/profiles/$profileSlug'
      fullPath: '/orgs/$slug/profiles/$profileSlug/'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings'
      path: '/orgs/$slug/profiles/$profileSlug'
      fullPath: '/orgs/$slug/profiles/$profileSlug'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/orders/$orderId': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/orders/$orderId'
      path: '/orgs/$slug/profiles/$profileSlug/orders/$orderId'
      fullPath: '/orgs/$slug/profiles/$profileSlug/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/settings': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/settings'
      path: '/settings'
      fullPath: '/orgs/$slug/profiles/$profileSlug/settings'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/details': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/_profile-settings/details'
      path: '/details'
      fullPath: '/orgs/$slug/profiles/$profileSlug/details'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRouteImport
      parentRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute
    }
  }
}

interface AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteChildren {
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute
}

const AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteChildren: AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteChildren =
  {
    AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute:
      AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsDetailsRoute,
    AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute:
      AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsSettingsRoute,
  }

const AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteWithChildren =
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute._addFileChildren(
    AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrgsNewRoute: typeof AuthenticatedOrgsNewRoute
  AuthenticatedOrgsSlugSettingsRoute: typeof AuthenticatedOrgsSlugSettingsRoute
  AuthenticatedOrgsSlugIndexRoute: typeof AuthenticatedOrgsSlugIndexRoute
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteWithChildren
  AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
  AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrgsNewRoute: AuthenticatedOrgsNewRoute,
  AuthenticatedOrgsSlugSettingsRoute: AuthenticatedOrgsSlugSettingsRoute,
  AuthenticatedOrgsSlugIndexRoute: AuthenticatedOrgsSlugIndexRoute,
  AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRoute:
    AuthenticatedOrgsSlugProfilesProfileSlugProfileSettingsRouteWithChildren,
  AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute:
    AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute,
  AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute:
    AuthenticatedOrgsSlugProfilesProfileSlugOrdersOrderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWebhooksWompiRoute: ApiWebhooksWompiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
