/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedOrgsNewRouteImport } from './routes/_authenticated/orgs/new'
import { Route as AuthenticatedOrgsSlugIndexRouteImport } from './routes/_authenticated/orgs/$slug/index'
import { Route as AuthenticatedOrgsSlugSettingsRouteImport } from './routes/_authenticated/orgs/$slug/settings'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugIndexRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/index'
import { Route as AuthenticatedOrgsSlugProfilesProfileSlugSettingsRouteImport } from './routes/_authenticated/orgs/$slug/profiles/$profileSlug/settings'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsNewRoute = AuthenticatedOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsSlugIndexRoute =
  AuthenticatedOrgsSlugIndexRouteImport.update({
    id: '/orgs/$slug/',
    path: '/orgs/$slug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugSettingsRoute =
  AuthenticatedOrgsSlugSettingsRouteImport.update({
    id: '/orgs/$slug/settings',
    path: '/orgs/$slug/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugIndexRouteImport.update({
    id: '/orgs/$slug/profiles/$profileSlug/',
    path: '/orgs/$slug/profiles/$profileSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute =
  AuthenticatedOrgsSlugProfilesProfileSlugSettingsRouteImport.update({
    id: '/orgs/$slug/profiles/$profileSlug/settings',
    path: '/orgs/$slug/profiles/$profileSlug/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/orgs/$slug/settings': typeof AuthenticatedOrgsSlugSettingsRoute
  '/orgs/$slug/': typeof AuthenticatedOrgsSlugIndexRoute
  '/orgs/$slug/profiles/$profileSlug/settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute
  '/orgs/$slug/profiles/$profileSlug/': typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/orgs/$slug/settings': typeof AuthenticatedOrgsSlugSettingsRoute
  '/orgs/$slug': typeof AuthenticatedOrgsSlugIndexRoute
  '/orgs/$slug/profiles/$profileSlug/settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute
  '/orgs/$slug/profiles/$profileSlug': typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/orgs/new': typeof AuthenticatedOrgsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_authenticated/orgs/$slug/settings': typeof AuthenticatedOrgsSlugSettingsRoute
  '/_authenticated/orgs/$slug/': typeof AuthenticatedOrgsSlugIndexRoute
  '/_authenticated/orgs/$slug/profiles/$profileSlug/settings': typeof AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute
  '/_authenticated/orgs/$slug/profiles/$profileSlug/': typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/dashboard'
    | '/api/uploadthing'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/new'
    | '/api/auth/callback'
    | '/orgs/$slug/settings'
    | '/orgs/$slug/'
    | '/orgs/$slug/profiles/$profileSlug/settings'
    | '/orgs/$slug/profiles/$profileSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/dashboard'
    | '/api/uploadthing'
    | '/legal/privacy'
    | '/legal/terms'
    | '/orgs/new'
    | '/api/auth/callback'
    | '/orgs/$slug/settings'
    | '/orgs/$slug'
    | '/orgs/$slug/profiles/$profileSlug/settings'
    | '/orgs/$slug/profiles/$profileSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/dashboard'
    | '/api/uploadthing'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_authenticated/orgs/new'
    | '/api/auth/callback'
    | '/_authenticated/orgs/$slug/settings'
    | '/_authenticated/orgs/$slug/'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/settings'
    | '/_authenticated/orgs/$slug/profiles/$profileSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/new': {
      id: '/_authenticated/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AuthenticatedOrgsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/': {
      id: '/_authenticated/orgs/$slug/'
      path: '/orgs/$slug'
      fullPath: '/orgs/$slug/'
      preLoaderRoute: typeof AuthenticatedOrgsSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/settings': {
      id: '/_authenticated/orgs/$slug/settings'
      path: '/orgs/$slug/settings'
      fullPath: '/orgs/$slug/settings'
      preLoaderRoute: typeof AuthenticatedOrgsSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/'
      path: '/orgs/$slug/profiles/$profileSlug'
      fullPath: '/orgs/$slug/profiles/$profileSlug/'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$slug/profiles/$profileSlug/settings': {
      id: '/_authenticated/orgs/$slug/profiles/$profileSlug/settings'
      path: '/orgs/$slug/profiles/$profileSlug/settings'
      fullPath: '/orgs/$slug/profiles/$profileSlug/settings'
      preLoaderRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrgsNewRoute: typeof AuthenticatedOrgsNewRoute
  AuthenticatedOrgsSlugSettingsRoute: typeof AuthenticatedOrgsSlugSettingsRoute
  AuthenticatedOrgsSlugIndexRoute: typeof AuthenticatedOrgsSlugIndexRoute
  AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute
  AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute: typeof AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrgsNewRoute: AuthenticatedOrgsNewRoute,
  AuthenticatedOrgsSlugSettingsRoute: AuthenticatedOrgsSlugSettingsRoute,
  AuthenticatedOrgsSlugIndexRoute: AuthenticatedOrgsSlugIndexRoute,
  AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute:
    AuthenticatedOrgsSlugProfilesProfileSlugSettingsRoute,
  AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute:
    AuthenticatedOrgsSlugProfilesProfileSlugIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
